### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by JaviRpo** [TongZhangzt/cordova-plugin-native-ringtones#4]
```
> node -v
v9.2.1
> npm -v
5.6.0
> cordova plugin add cordova-plugin-native-ringtones --save
Installing "cordova-plugin-native-ringtones" for android

Failed to install 'cordova-plugin-native-ringtones': CordovaError: Failed to fetch plugin cordova-plugin-media via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules\cordova-plugin-media" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\{user}\AppData\Roaming\npm-cache\_logs\2017-12-08T17_54_27_696Z-debug.log
    at C:\Users\{user}\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\fetch.js:205:33
    at _rejected (C:\Users\{user}\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:864:24)
    at C:\Users\{user}\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\{user}\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\{user}\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:808:41)
    at C:\Users\{user}\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:624:44
    at runSingle (C:\Users\{user}\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:137:13)
    at flush (C:\Users\{user}\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Error: Failed to fetch plugin cordova-plugin-media via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules\cordova-plugin-media" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\{user}\AppData\Roaming\npm-cache\_logs\2017-12-08T17_54_27_696Z-debug.log

[ERROR] An error occurred while running cordova plugin add cordova-plugin-native-ringtones --save (exit code 1).
```

**Comment by TongZhangzt** [comment]
try  `cordova plugin add cordova-plugin-native-ringtones --nofetch --save`

**Comment by JaviRpo** [comment]
Thanks, 

The problem was with the plugin *cordova-plugin-media*
